# Generated by Django 4.1.7 on 2023-02-27 08:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.ImageField(default='profile.png', upload_to='')),
                ('mobile_number', models.CharField(max_length=10)),
                ('location', models.CharField(choices=[('Nairobi', 'Nairobi'), ('Mombasa', 'Mombasa'), ('Mt Kenya', 'Mt Kenya')], max_length=200)),
                ('gas_brand', models.CharField(choices=[('K-gas', 'K-gas'), ('Total', 'Total'), ('Progas', 'Progas')], max_length=200)),
                ('gas_size', models.CharField(choices=[('6kgs', '6kgs'), ('13kgs', '13kgs')], max_length=20)),
                ('married', models.BooleanField(default=False)),
                ('household_number', models.IntegerField()),
                ('kids_number', models.IntegerField(default=0)),
                ('kids_below3', models.IntegerField(default=0)),
                ('cooking_sequence', models.IntegerField()),
                ('cooking_method', models.CharField(choices=[('Microwaving', 'Microwaving'), ('Stir-frying', 'Stir-frying'), ('Broiling', 'Broiling'), ('Steaming', 'Steaming'), ('Baking', 'Baking'), ('Roasting', 'Roasting'), ('Boiling', 'Boiling'), ('Simmering', 'Simmering')], max_length=200)),
                ('last_refillspan', models.IntegerField()),
                ('updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
