# Generated by Django 4.1.7 on 2023-02-27 08:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='cooking_method',
            field=models.CharField(choices=[('Microwaving', 'Microwaving'), ('Stir-frying', 'Stir-frying'), ('Broiling', 'Broiling'), ('Steaming', 'Steaming'), ('Baking', 'Baking'), ('Roasting', 'Roasting'), ('Boiling', 'Boiling'), ('Simmering', 'Simmering')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='cooking_sequence',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gas_brand',
            field=models.CharField(choices=[('K-gas', 'K-gas'), ('Total', 'Total'), ('Progas', 'Progas')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gas_size',
            field=models.CharField(choices=[('6kgs', '6kgs'), ('13kgs', '13kgs')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='household_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='kids_below3',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='kids_number',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_refillspan',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.CharField(choices=[('Nairobi', 'Nairobi'), ('Mombasa', 'Mombasa'), ('Mt Kenya', 'Mt Kenya')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='married',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='mobile_number',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='pic',
            field=models.ImageField(default='profile.png', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='profile',
            name='updated',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
