# Generated by Django 4.1.5 on 2023-03-20 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_profile_last_refillspan_profile_last_refill'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='predicted_refill',
            field=models.DateField(null=True),
        ),
    ]
