# Generated by Django 4.1.7 on 2023-04-11 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_saving_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saving',
            name='balance',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.FloatField(),
        ),
    ]
