# Generated by Django 4.1.7 on 2023-04-12 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_saving_balance_alter_transaction_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saving',
            name='balance',
            field=models.FloatField(default=0.0),
        ),
    ]
