# Generated by Django 4.1.7 on 2023-04-12 07:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_saving_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saving',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='savings', to=settings.AUTH_USER_MODEL, unique=True),
        ),
    ]
